set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'lepture/vim-jinja'
Plugin 'davidhalter/jedi-vim'

Plugin 'airblade/vim-gitgutter'
" ]c jump to next hunk (change) 
" [c jump to previous hunk (change) 

Plugin 'vim-airline/vim-airline'
Plugin 'wincent/command-t'
Plugin 'scrooloose/nerdTree'
Plugin 'scrooloose/syntastic'
Plugin 'vim-scripts/ctrlp.vim'
Plugin 'vim-multiple-cursors'
Plugin 'tpope/vim-surround'
"Commands for surround plugin
"ds<character>                  Delete surrounding <character>
"cs<character><new character>   Replace surrounding <character> with <newcharacter>
"ys<text-obj><character>        Surround text-object with <character>
"dst                            Delete surround tag (works on HTML tags)

Plugin 'tpope/vim-commentary'
"Commands for Commenting"
"gc2j   Comment down two lines
"gcc    Comment out the current line
"gcip   Comment out the current paragraph

Plugin 'tpope/vim-repeat'

Plugin 'mattn/emmet-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
" filetype plugin indent on    " required
autocmd BufWritePre *.* :%s/\s\+$//e
" set number " show ruler
set relativenumber
set colorcolumn=80
set nowrap
set expandtab
set shiftwidth=4
set softtabstop=4
set cursorline  "Add line below the active line unde cursor
colo Monokai   " skin name
syntax on
"Highlight the active split
nmap 0 ^
nmap k gk
nmap j gj
" Add some syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0 
let g:syntastic_check_on_open = 0 
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['jshint', 'jscs']
let g:syntastic_mode_map = { 'passive_filetypes': ['python'] }
let g:ctrlp_use_caching = 0
let g:ctrlp_max_files=0
